git:
    depth: 10

language: php

matrix:
  include:
    - php: 7.1
      sudo: false
    - php: 7.2
      sudo: false

cache:
    directories:
        - $HOME/.composer/cache

install:
    - rm $HOME/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini;
    - echo "memory_limit=2048M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer install

script:
    - bin/phpunit

