git:
    depth: 10

language: php

matrix:
  include:
    - php: 7.1
      sudo: false
      env: UNIT_TESTS=true
    - php: 7.2
      sudo: false
      env: UNIT_TESTS=true

cache:
    directories:
        - $HOME/.composer/cache

install:
    - rm $HOME/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini;
    - echo "memory_limit=2048M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - composer install

script:
    - PKG_PHP_CHANGED_FILES=`./bin/git-find-changed-php-files.sh "${TRAVIS_COMMIT_RANGE}"`
    - if [ "$UNIT_TESTS" = true ]; then bin/phpunit --exclude-group=functional; fi  

